[package]
name = "android-mic-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
byteorder = "1.4.3"
rtrb = "0.2.3"
crossterm = {version = "0.27.0"}
clap = { version = "4.3.19", features = ["derive"] }
