[package]
name = "android-mic-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15"
byteordered = "0.6"
rtrb = "0.2"
crossterm = {version = "0.27"}
clap = { version = "4.3", features = ["derive"] }
strum = { version = "0.25", features = ["derive"] }
local-ip-address = "0.5"
